credentials:
  usernames:
    admin:
      name: admin
      password: adminpass
    demo:
      name: demo
      password: demodemo
cookie:
  expiry_days: 15
  key: random_signature_key
  name: random_cookie_name
